// Generated by gencpp from file yolov5/vision.msg
// DO NOT EDIT!


#ifndef YOLOV5_MESSAGE_VISION_H
#define YOLOV5_MESSAGE_VISION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov5
{
template <class ContainerAllocator>
struct vision_
{
  typedef vision_<ContainerAllocator> Type;

  vision_()
    : jarak_objek(0)  {
    }
  vision_(const ContainerAllocator& _alloc)
    : jarak_objek(0)  {
  (void)_alloc;
    }



   typedef int64_t _jarak_objek_type;
  _jarak_objek_type jarak_objek;





  typedef boost::shared_ptr< ::yolov5::vision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov5::vision_<ContainerAllocator> const> ConstPtr;

}; // struct vision_

typedef ::yolov5::vision_<std::allocator<void> > vision;

typedef boost::shared_ptr< ::yolov5::vision > visionPtr;
typedef boost::shared_ptr< ::yolov5::vision const> visionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov5::vision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov5::vision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov5::vision_<ContainerAllocator1> & lhs, const ::yolov5::vision_<ContainerAllocator2> & rhs)
{
  return lhs.jarak_objek == rhs.jarak_objek;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov5::vision_<ContainerAllocator1> & lhs, const ::yolov5::vision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov5::vision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov5::vision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5::vision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5::vision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5::vision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5::vision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov5::vision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5db1e3e1b216d22cf080e8124bd6b36";
  }

  static const char* value(const ::yolov5::vision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5db1e3e1b216d22ULL;
  static const uint64_t static_value2 = 0xcf080e8124bd6b36ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov5::vision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov5/vision";
  }

  static const char* value(const ::yolov5::vision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov5::vision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 jarak_objek\n"
;
  }

  static const char* value(const ::yolov5::vision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov5::vision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jarak_objek);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov5::vision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov5::vision_<ContainerAllocator>& v)
  {
    s << indent << "jarak_objek: ";
    Printer<int64_t>::stream(s, indent + "  ", v.jarak_objek);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV5_MESSAGE_VISION_H
